### ISSUE TITLE
Request for gitlab, github and a few more icons

### ISSUE THREAD

**Issue by kvistgaard** [rcvd/magic-tags#5]
It would be nice to add:

- [ ] gitlab
- [ ] github
- [ ] chevrons-left
- [ ] chevrons-right
- [ ] credit card

I was looking also for something for finance (money, bank, banknotes) in Feather but could no find anything appropriate.

**Comment by rcvd** [comment]
What about mixing in icons from here https://lucide.dev/ ?

**Comment by kvistgaard** [comment]
I guess it should work.
Any chance of having the icon itself in the drop-down?

**Comment by rcvd** [comment]
Icons added as requested - UI changes are hard to implement
